definitions:
  login.LoginRequest:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  login.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  model.CPUInfo:
    properties:
      cores_num:
        type: integer
      cpu_info_created_at:
        description: 添加 CreatedAt 字段
        type: string
      id:
        description: 添加 ID 字段
        type: integer
      model_name:
        type: string
      percent:
        type: number
    type: object
  model.HostInfo:
    properties:
      host_info_created_at:
        description: 添加 CreatedAt 字段
        type: string
      hostname:
        type: string
      id:
        description: 添加 ID 字段
        type: integer
      kernel_arch:
        type: string
      os:
        type: string
      platform:
        type: string
      token:
        type: string
    type: object
  model.MemoryInfo:
    properties:
      available:
        type: string
      free:
        type: string
      id:
        description: 添加 ID 字段
        type: integer
      mem_info_created_at:
        description: 添加 CreatedAt 字段
        type: string
      total:
        type: string
      used:
        type: string
      user_percent:
        type: number
    type: object
  model.NetworkInfo:
    properties:
      bytes_recv:
        description: 接收字节数
        type: integer
      bytes_sent:
        description: 发送字节数
        type: integer
      id:
        type: integer
      name:
        type: string
      net_info_created_at:
        type: string
    type: object
  model.ProcessInfo:
    properties:
      cmdline:
        type: string
      cpu_percent:
        type: number
      id:
        description: 添加 ID 字段
        type: integer
      mem_percent:
        type: number
      pid:
        type: integer
      pro_info_created_at:
        description: 添加 CreatedAt 字段
        type: string
    type: object
  monitor.RequestData:
    description: RequestData 包含所有需要收集的系统信息
    properties:
      cpu_info:
        description: CPU 信息
        items:
          $ref: '#/definitions/model.CPUInfo'
        type: array
      host_info:
        allOf:
        - $ref: '#/definitions/model.HostInfo'
        description: 主机信息
      mem_info:
        allOf:
        - $ref: '#/definitions/model.MemoryInfo'
        description: 内存信息
      net_info:
        allOf:
        - $ref: '#/definitions/model.NetworkInfo'
        description: 网络信息
      pro_info:
        description: 进程信息
        items:
          $ref: '#/definitions/model.ProcessInfo'
        type: array
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: 用于用户登录，需要提供用户名和密码，并返回JWT token。
      parameters:
      - description: 登录信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/login.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求数据格式错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 用户不存在或密码错误
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - Auth
  /monitor:
    post:
      consumes:
      - application/json
      description: 该API用于接收客户端发送的系统监控数据，并验证token和JWT后将数据存储到数据库中。
      parameters:
      - description: 请求体包含系统监控数据
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/monitor.RequestData'
      produces:
      - application/json
      responses:
        "201":
          description: 成功响应
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 无效的JSON数据或令牌长度错误
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: 授权头缺失或无效的token格式或无效的JWT token
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 数据库操作失败
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 接收系统监控信息（CPU、内存、主机信息等）
      tags:
      - Monitor
  /register:
    post:
      consumes:
      - application/json
      description: 通过提供用户名、邮箱和密码来注册新用户。
      parameters:
      - description: 注册信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/login.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: 请求数据格式错误
          schema:
            additionalProperties:
              type: string
            type: object
        "422":
          description: 用户名或邮箱验证失败
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 服务器内部错误
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户注册
      tags:
      - User
swagger: "2.0"
